### ISSUE TITLE
Allow labels to be added to the resulting secret

### ISSUE THREAD

**Issue by Chumper** [ricoberger/vault-secrets-operator#138]
I am currently working on setting up [ArgoCD](https://argo-cd.readthedocs.io/en/stable/) with the vault-secret-operator.

ArgoCD supports that credentials for git repository access can be declared beforehand:
https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials

Example:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: first-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/argoproj/private-repo
```

ArgoCD relies on the labels to determine that a secret belongs to an ArgoCD installation.
So I would like to request that (in the easiest implementation) we can labels to the secret as well.

For my usecase it should be sufficient to add labels as an additional field in the spec:
```yaml
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: example-secret
spec:
  keys:
    - url
  path: kvv1/example-vaultsecret
  type: Opaque
  labels:
    argocd.argoproj.io/secret-type: repository
```

Which would result in a secret like this:
```yaml
apiVersion: v1
data:
  url: YmFyCg==
kind: Secret
metadata:
  labels:
    created-by: vault-secrets-operator
    argocd.argoproj.io/secret-type: repository
  name: example-secret
type: Opaque
```

I am not sure yet if this affects ArgoCD because the secrets are stored in `data` instead `stringData` but that should not be a concern here.

If needed I can try myself out by contributing this. I would expect it to be a rather simple change.

**Comment by ricoberger** [comment]
Hi @Chumper, we are already propagating the labels from the VaultSecret to the Kubernetes Secret:

```yaml
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: example-secret
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  keys:
    - url
  path: kvv1/example-vaultsecret
  type: Opaque
```

The above VaultSecret would result in a secret like this:

```yaml
apiVersion: v1
data:
  url: YmFyCg==
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: example-secret
type: Opaque
```

Does this already help for your use case?
