### ISSUE TITLE
[Feature request] Multiple types of secrets

### ISSUE THREAD

**Issue by dieser94** [ricoberger/vault-secrets-operator#14]
Hello, I stumbled upon this repo while looking for solutions with vault secret syncing, until now this looks like the most classy way of doing this but the only question I have is if there are any plans in the near future to support different types of secrets (files, tls, docker artifactory).

**Comment by ricoberger** [comment]
Hi, this should work. For example: If you would create the following Docker secret

```sh
kubectl create secret docker-registry registry --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL
```

the corresponding secret in Vault looks like this:

```sh
vault secrets enable -path=kvv1 -version=1 kv

vault kv put kvv1/registry .dockerconfigjson='{"auths":{"DOCKER_REGISTRY_SERVER":{"username":"DOCKER_USER","password":"DOCKER_PASSWORD","email":"DOCKER_EMAIL","auth":"RE9DS0VSX1VTRVI6RE9DS0VSX1BBU1NXT1JE"}}}'
```

This Vault secret can be used with the following CR. The important thing here is to set the `spec.type` field to `kubernetes.io/dockerconfigjson`.

```yaml
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: registry
spec:
  keys:
    - .dockerconfigjson
  path: kvv1/registry
  type: kubernetes.io/dockerconfigjson
```

This should also work for a secret that contains a TLS private key and certificate:

```yaml
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: certificate
spec:
  keys:
    - tls.crt
    - tls.key
  path: kvv1/certificate
  type: kubernetes.io/tls
```

This would assume that you have a Vault secret named `certificate` with a key `tls.crt` and `tls.key` containing the certificate and the private key.

**Comment by dieser94** [comment]
Thank you very much! One last question, is there any way of giving the Vault Token from a mounted volume?
Up until now I've been using Vault Agent to do the Auth part and storing the token to be used.

**Comment by ricoberger** [comment]
Hi, no problem. The recommended approach for authentication is the **Kubernetes Auth Method**. Therefor the service account is used for authentication and it is not necessary to store the token.

```yaml
vault:
  address: "http://vault:8200"
  authMethod: kubernetes
  kubernetesPath: auth/kubernetes
  kubernetesRole: vault-secrets-operator

serviceAccount:
  create: true
  name: vault-secrets-operator
```

If you want to use the **Token Auth Method** you can pass the token via secret to the operator.

```sh
kubectl create secret generic vault-secrets-operator --from-literal=VAULT_TOKEN=<TOKEN> --from-literal=VAULT_TOKEN_LEASE_DURATION=86400
```

```yaml
environmentVars:
  - envName: VAULT_TOKEN
    secretName: vault-secrets-operator
    secretKey: VAULT_TOKEN
  - envName: VAULT_TOKEN_LEASE_DURATION
    secretName: vault-secrets-operator
    secretKey: VAULT_TOKEN_LEASE_DURATION

vault:
  address: "http://vault:8200"
  authMethod: token
```
