### ISSUE TITLE
invalid secret name

### ISSUE THREAD

**Issue by artarik** [ricoberger/vault-secrets-operator#156]
Hello
I create a secret for nginx where key is file path and value is cert in base64
If i try to use it i get an eror

`...."reconciler kind":"VaultSecret","name":"wildcart-cert","namespace":"vault","error":"Secret \"wildcart-cert\" is invalid: data[/etc/nginx/certificates/wildcard.cert]: Invalid value: \"/etc/nginx/certificates/wildcard.cert\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')"...`
Can you change regex for keys?

**Comment by ricoberger** [comment]
Hi @artarik, I do not think that this error is coming from the operator himself. If I get it right your secret in Vault contains a key value pair with the following information:

- key: /etc/nginx/certificates/wildcard.cert
- value: <your base64 encoded cert>

If this is the case, it fails because the operator tries to use the `key` as the name for the data field in the Kubernetes secret:

```yaml
apiVersion: v1
kind: Secret
data:
  /etc/nginx/certificates/wildcard.cert: <your base64 encoded cert>
```

Since `/` isn't [allowed](https://kubernetes.io/docs/concepts/configuration/secret/#restriction-names-data) in a Kubernetes the creation fails with the above error.

**Comment by artarik** [comment]
Is there any way I can get my key from vault and put it in k8s secret?

**Comment by ricoberger** [comment]
If you can change the key in vault to just `wildcard.cert` it should work.

If this is not possible you can also try to use the templating feature of the operator to use another key for the created Kubernetes secret as shown in the following:

```yaml
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
spec:
  path: <PATH>
  templates:
    wildcard.cert: "{% .Secrets['/etc/nginx/certificates/wildcard.cert'] %}"
```
