### ISSUE TITLE
Add support for RabbitMQ secret engine

### ISSUE THREAD

**Issue by ThiagoFelippi** [ricoberger/vault-secrets-operator#200]
I'm using the vault-secrets-operator with kv `secretEngine`, but now I'm migrating the RabbitMQ to use credentials from RabbitMQ secret engine at Vault. So I like to suggest the implementation of RabbitMQ secretEngine.

To get the credentials with CLI: `vault read rabbitmq/creds/my-role`
An idea of CRD manifest, could be:
```
  apiVersion: ricoberger.de/v1alpha1
  kind: VaultSecret
  metadata:
    name: test-rabbit
  spec:
    secretEngine: rabbitmq
    role: my-vhost
    path: rabbitmq
    type: Opaque
```
