### ISSUE TITLE
[Feature Request] Single secret from multiple vault paths

### ISSUE THREAD

**Issue by dimaj** [ricoberger/vault-secrets-operator#292]
Hi Rico,

Thanks for the amazing operator!

I have a small feature request. Create a single secret from multiple secret paths. I would like to have a manifest similar to this:
```
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: prometheus-scrape-configs
  namespace: monitoring
spec:
  keys:
    - kuma_password
  paths:
    - kv2/ORG/secret1
    - kv2/ORG/secret2
   type: Opaque
```

p.s. I am not sure if this is related to issue #168 

Thanks!
