### ISSUE TITLE
Howto configure custom CA

### ISSUE THREAD

**Issue by gites** [ricoberger/vault-secrets-operator#35]
I want to configure `vault-secrets-operator` to use my custom CA when connecting to Vault but without using mTLS (so no client cert and key). I've followed instructions in https://github.com/ricoberger/vault-secrets-operator/pull/28 , created a secret with the ca file and corresponding ENV mapping.

Secret:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-pem-vault-secrets-operator
  namespace: ops
data:
  ca-pem: ...
```
ENV mapping:
```
            - name: VAULT_CACERT
              valueFrom:
                secretKeyRef:
                  name: ca-pem-vault-secrets-operator
                  key: ca-pem
```

When I try to deploy this I'm getting the following error:
```
{"level":"error","ts":1588665097.7746422,"logger":"cmd","msg":"Could not create API client for Vault","error":"error encountered setting up default configuration: Error loading CA File: open -----BEGIN CERTIFICATE-----<cert data here>-----END CERTIFICATE-----\n: no such file or directory","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tvault-secrets-operator/cmd/manager/main.go:88\nruntime.main\n\t/opt/hostedtoolcache/go/1.13.8/x64/src/runtime/proc.go:203"}
```
So it looks like the `VAULT_CACERT` should point to a file (see the `Error loading CA File: open`)

When I do a volume mount and set the `VAULT_CACERT` value to file with the CA the error message is:
```
{"level":"error","ts":1588665658.6766431,"logger":"cmd","msg":"Could not create API client for Vault","error":"no certs found in root CA file","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nmain.main\n\tvault-secrets-operator/cmd/manager/main.go:88\nruntime.main\n\t/opt/hostedtoolcache/go/1.13.8/x64/src/runtime/proc.go:203"}
```
Any ideas what I'm missing here?
