### ISSUE TITLE
Creating image pull secrets?

### ISSUE THREAD

**Issue by jiphex** [ricoberger/vault-secrets-operator#54]
I'm just interested if anyone's got a good way to use vault-secrets-operator to generate Kubernetes-compatible Image Pull Secrets?

I realise that I could do this (I think) by creating a `VaultSecret` object referencing a path in Vault which stores a _raw_ `.dockerconfigjson` style key (as shown in [a previous issue](!14)), but I guess really I'd like the keys in the Vault secret to be stored with more useful keys (e.g `docker-server`,`docker-password` etc like you can do with `kubectl create secret docker-registry`).

Maybe I can just implement this with the [templates](!53) proposed by @bartmeuris, but I feel like this is something that people must have hit before and had a way of sorting?

**Comment by ricoberger** [comment]
Hi @jiphex, we are still creating image pull secrets in the way mentioned in the linked issue (#14). Since @bartmeuris PR is merged now and available in the latest release [1.9.0](https://github.com/ricoberger/vault-secrets-operator/releases/tag/1.9.0), we may switch to this approach.

**Comment by jiphex** [comment]
Thanks ricoberger that's useful

**Comment by jiphex** [comment]
Just in case someone comes across this in future, I've made this work now using the templates support from [1.9.0](https://github.com/ricoberger/vault-secrets-operator/releases/tag/1.9.0)

```
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: an-image-pull-secret
spec:
  path: secret/some-vault-path
  type: kubernetes.io/dockerconfigjson
  templates:
    .dockerconfigjson: '{"auths":{"hostname.of.registry.com":{"username":"{% .Secrets.username %}","password":"{% .Secrets.token %}"}}}'
```
