### ISSUE TITLE
Cosmetic changes to kustomize

### ISSUE THREAD

**Issue by fernando-villalba** [ricoberger/vault-secrets-operator#71]
Just wanted to suggest a couple of changes that may make it easier for you and more legible (and usable) for others, feel free to close and disregard if it doesn't feel natural to you.

In [here](https://github.com/ricoberger/vault-secrets-operator/blob/master/config/default/kustomization.yaml) you have this: 

```
# Adds namespace to all resources.
namespace: vault-secrets-operator

bases:
- ../crd
- ../rbac
- ../manager
```

The `bases` field is [deprecated](https://kubectl.docs.kubernetes.io/references/kustomize/bases/)

Also I am guessing your bases are more static than your version, so it may make more sense to set the version of the image to latest in the base, but then do this in the kustomization file (or do both): 

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Adds namespace to all resources.
namespace: vault-secrets-operator

resources:
- ../crd
- ../rbac
- ../manager

images:
  - name: ricoberger/vault-secrets-operator
    newTag: 1.11.0

```

Again, feel free to close and disregard if these changes don't suit you as it's mostly cosmetic. It's still amazing you are maintaining kustomize deployment so I can track it and this will work either way:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
  - https://github.com/ricoberger/vault-secrets-operator/config/default?ref=1.11.0

patchesStrategicMerge:
- overlays/deploy.yaml

images:
  - name: ricoberger/vault-secrets-operator
    newTag: 1.11.0

```
